# Generated by Django 3.1 on 2021-01-13 03:37

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=20, verbose_name='Tên')),
                ('slug', models.SlugField(default='', editable=False, max_length=20)),
                ('cat_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
            bases=(app.models.CategoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=255, verbose_name='Tên')),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Mô tả')),
                ('price_import', models.FloatField(verbose_name='Gias nhập')),
                ('price_sell', models.FloatField(verbose_name='Giá bán')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='Giảm giá')),
                ('qty', models.FloatField(verbose_name='Số lượng')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_create', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.category', verbose_name='Nhóm')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
