# Generated by Django 3.1 on 2021-01-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210113_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
