# Generated by Django 3.1 on 2021-01-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_publisher_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_create',)},
        ),
    ]
