# Generated by Django 3.1 on 2021-01-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Giảm giá'),
        ),
    ]
