# Generated by Django 3.1 on 2021-02-17 10:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_productlastvisit_termofuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termofuse',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
