# Generated by Django 3.1 on 2021-02-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20210205_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='static/user/profilepic.png', null=True, upload_to='static/user'),
        ),
    ]
